### ISSUE TITLE
401 unauthorized 

### ISSUE THREAD

**Issue by purplescorpion1** [cabernetwork/cabernet#115]
I get everything set up and it works for a few hours. Then when I go to play something again I get 401 unauthorized error. Even if I reset the channel data and restart the server it still happens. The only way I fixed it was by uninstalling everything and reinstalling everything but then again it only works for a while and I get 401 unauthorized again.

Here is the log running the latest RC version

`
2023-12-02 18:52:01,240-ERROR:web_admin UNEXPECTED EXCEPTION on POST=HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Program Files\cabernet\lib\clients\web_admin.py", line 145, in do_POST
    if postrequest.call_url(self, self.content_path):
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 311, in call_url
    self.url2func[_name](_webserver, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\config\configform_html.py", line 54, in post_configform_html
    results = _webserver.plugins.config_obj.update_config(area, config_changes)
  File "C:\Program Files\cabernet\lib\config\user_config.py", line 259, in update_config
    results += self.defn_json.call_onchange(_area, _updated_data, self)
  File "C:\Program Files\cabernet\lib\config\config_defn.py", line 154, in call_onchange
    status = self.call_function(setting_data['onChange'], section, key, _config_obj)
  File "C:\Program Files\cabernet\lib\config\config_defn.py", line 185, in call_function
    return func(_config_obj, _section, _key)
  File "C:\Program Files\cabernet\lib\config\config_callbacks.py", line 76, in logging_enable
    logging_refresh(_config_obj, _section, _key)
  File "C:\Program Files\cabernet\lib\config\config_callbacks.py", line 61, in logging_refresh
    with urllib.request.urlopen(req) as resp:
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
2023-12-02 18:52:01,480-WARNING:web_handler [192.168.1.193] "POST /api/configform HTTP/1.1" 501 -

`

**Comment by purplescorpion1** [comment]
Think it might have been my fault changing the default ip address in settings

**Comment by purplescorpion1** [comment]
fixed it after reverting client settings to defaults
