### ISSUE TITLE
epg update failes for daddlive

### ISSUE THREAD

**Issue by vortex91** [cabernetwork/cabernet#116]
updated to latest Version: 0.9.14.00-RC05 and now epg update fails.

2023-12-06 20:18:16,917-DEBUG:schedule Running job Job(interval=1, unit=days, do=exec_trigger, args=({'uuid': '17F1F799-94B4-11EE-874C-D77CFC6C27E1', 'area': 'EPG', 'title': 'Refresh DaddyLive EPG', 'timetype': 'daily', 'timelimit': -1, 'timeofday': '06:11', 'dayofweek': None, 'interval': -1, 'randdur': -1, 'taskid': '17F1F797-94B4-11EE-874C-D77CFC6C27E1', 'namespace': 'DaddyLive', 'instance': None, 'funccall': 'refresh_epg', 'lastran': None, 'duration': None, 'priority': 10, 'threadtype': 'thread', 'active': 0, 'description': 'Pulls channel program data from DaddyLive'},), kwargs={})
2023-12-06 20:18:16,940-NOTICE:scheduler Running threaded task EPG:Refresh DaddyLive EPG
2023-12-06 20:18:16,958-DEBUG:web_handler [127.0.0.1] "GET /api/schedulehtml?task=17F1F797-94B4-11EE-874C-D77CFC6C27E1&run=1 HTTP/1.0" 200 -
2023-12-06 20:18:17,031-DEBUG:web_handler [127.0.0.1] "GET /modules/scheduler/scheduler.css HTTP/1.0" 200 -
2023-12-06 20:18:17,091-DEBUG:web_handler [127.0.0.1] "GET /modules/scheduler/scheduler.js HTTP/1.0" 200 -
2023-12-06 20:18:21,324-WARNING:decorators get uri called from <function PluginEPG.get_uri_data at 0x7fc344c52710> with retires=2
2023-12-06 20:18:21,819-ERROR:scheduler UNEXPECTED EXCEPTION on GET=list index out of range
Traceback (most recent call last):
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/schedule/scheduler.py", line 157, in call_trigger
    results = call_f()
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/plugins/plugin_obj.py", line 228, in refresh_epg
    return self.refresh_it('EPG', _instance)
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/plugins/plugin_obj.py", line 243, in refresh_it
    instance.refresh_epg()
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/plugins/plugin_instance_obj.py", line 166, in refresh_epg
    return self.epg.refresh_epg()
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/plugins/plugin_epg.py", line 85, in refresh_epg
    self.refresh_programs(epg_day, False)
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/plugins_ext/provider_video_daddylive/lib/epg.py", line 59, in refresh_programs
    program_list = self.get_fullday_programs(_epg_day)
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/plugins_ext/provider_video_daddylive/lib/epg.py", line 94, in get_fullday_programs
    .get_channel_day_ext(epg_id[0], epg_id[1], start_seconds)
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/plugins/plugin_obj.py", line 108, in get_channel_day_ext
    return self.instances[_instance].get_channel_day(_zone, _uid, _day)
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/lib/plugins/plugin_instance_obj.py", line 102, in get_channel_day
    return self.epg.get_channel_day(_zone, _uid, _day)
  File "/home/vortex91/Downloads/cabernet-0.9.11.05/plugins_ext/provider_epg_tvguide/lib/epg.py", line 61, in get_channel_day
    json_data = json_data['data']['items'][0]['programSchedules']
IndexError: list index out of range
2023-12-06 20:18:22,384-DEBUG:web_handler [127.0.0.1] "GET /api/schedulehtml?EPG=1& HTTP/1.0" 200 -
2023-12-06 20:18:22,438-DEBUG:web_handler [127.0.0.1] "GET /modules/scheduler/scheduler.css HTTP/1.0" 200 -
2023-12-06 20:18:22,451-DEBUG:web_handler [127.0.0.1] "GET /modules/scheduler/scheduler.js HTTP/1.0" 200 -

**Comment by rocky4546** [comment]
fixed already in rc06.

**Comment by vortex91** [comment]
with rc06 error is gone but it seems like its in a loop and never finishes update...

2023-12-06 23:22:07,129-DEBUG:web_handler [127.0.0.1] "GET /api/dashstatus.json HTTP/1.0" 200 -
2023-12-06 23:22:07,391-INFO:decorators Socket Timeout Error in function PluginPrograms.get_uri_data(), retrying 829957 HTTPSConnectionPool(host='fandom-prod.apigee.net', port=443): Read timed out. (read timeout=8) https://fandom-prod.apigee.net/v1/xapi/tvschedules/tvguide/programdetails/6033698257/web
2023-12-06 23:22:08,392-NOTICE:decorators Multiple HTTP Errors, unable to get url data, skipping PluginPrograms.get_uri_data() 829957 HTTPSConnectionPool(host='fandom-prod.apigee.net', port=443): Read timed out. (read timeout=8) https://fandom-prod.apigee.net/v1/xapi/tvschedules/tvguide/programdetails/6033698257/web
2023-12-06 23:22:08,392-NOTICE:epg Program error: EPG program details missing DaddyLive 6033698257
2023-12-06 23:22:08,393-WARNING:decorators get uri called from <function PluginPrograms.get_uri_data at 0x7f5dbd021d80> with retires=2
2023-12-06 23:22:09,181-DEBUG:web_handler [127.0.0.1] "GET /tunerstatus HTTP/1.1" 200 -

**Comment by rocky4546** [comment]
Nope, normal.  TVGUIDE says it has a program available, but when you ask for it, it does not exist.  No issue.
