### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by MartinR577** [cabernetwork/cabernet#120]
Trying a new install on a windows 10 system. 
UnZipped to a folder
First launch created the Config.ini but exited immediately with an error about the config.ini is empty 
Added the following to the config.ini 

[plutotv_default]
label = PlutoTV Instance
enabled = True

Launched Cabernet again. Added the PlutoTV plugin 
on restart i get the following:

C:\apps\cabernet>python3 tvh_main.py
2023-12-21 01:52:25,828-WARNING:main #########################################
2023-12-21 01:52:25,828-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546
Traceback (most recent call last):
  File "C:\apps\cabernet\tvh_main.py", line 41, in <module>
    main.main(script_dir)
  File "C:\apps\cabernet\lib\main.py", line 150, in main
    pickle_it.to_pickle(plugins)
  File "C:\apps\cabernet\lib\common\pickling.py", line 44, in to_pickle
    pickle.dump(_object_to_pickle, f, -1)
TypeError: cannot pickle '_thread.RLock' object

**Comment by AFrameWorker** [comment]
Can confirm, I have the same issue with the latest RC8 update as well. RC7 works perfectly fine.

**Comment by rocky4546** [comment]
Looking into this issue.  Pickling is a function for Windows to get around its limitation on forking processes.

**Comment by rocky4546** [comment]
Should be fixed in RC09

**Comment by purplescorpion1** [comment]
> Should be fixed in RC09

nope - updated direct from RC07 to RC09 and get

```
2023-12-21 22:19:32,513-WARNING:main #########################################
2023-12-21 22:19:32,513-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546
Traceback (most recent call last):
  File "tvh_main.py", line 41, in <module>
    main.main(script_dir)
  File "C:\Program Files\cabernet\lib\main.py", line 150, in main
    pickle_it.to_pickle(plugins)
  File "C:\Program Files\cabernet\lib\common\pickling.py", line 44, in to_pickle
    pickle.dump(_object_to_pickle, f, -1)
TypeError: cannot pickle '_thread.RLock' object
```

**Comment by rocky4546** [comment]
yea, got the same results.  Trying to fix this with covid, so brain is kinda mush.

**Comment by rocky4546** [comment]
ok, I think I fixed it in RC11.  github messed up RC10, so had to move to RC11.

**Comment by purplescorpion1** [comment]
> ok, I think I fixed it in RC11. github messed up RC10, so had to move to RC11.

yep all good now thanks

**Comment by rocky4546** [comment]
I get all types of errors from DL.  There are days that are a mess while other days a clean as a whistle.  Have not seen the same issues on the other plugins.

**Comment by purplescorpion1** [comment]
So I had it on ffmpeg and that gave me parser errors and error 400 when playing a stream
Switched to internal proxy and it doesn't play at all -  loads of errors in log

```
AttributeError: 'NoneType' object has no attribute 'get'
2023-12-22 01:35:36,446-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\cabernet\lib\clients\web_tuner.py", line 129, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 291, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\clients\web_tuner.py", line 53, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "C:\Program Files\cabernet\lib\clients\web_tuner.py", line 219, in do_tuning
    self.ffmpeg_proxy.stream(station_data, self.wfile, resp['tuner'])
  File "C:\Program Files\cabernet\lib\streams\ffmpeg_proxy.py", line 73, in stream
    channel_uri = self.get_stream_uri(self.channel_dict)
  File "C:\Program Files\cabernet\lib\streams\stream.py", line 87, in get_stream_uri
    return self.plugins.plugins[_channel_dict['namespace']] \
  File "C:\Program Files\cabernet\lib\plugins\plugin_obj.py", line 106, in get_channel_uri_ext
    return self.instances[_instance].get_channel_uri(_sid)
  File "C:\Program Files\cabernet\lib\plugins\plugin_instance_obj.py", line 85, in get_channel_uri
    return self.channels.get_channel_uri(sid)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 85, in get_channel_uri
    ch_url = self.get_channel_ref(_channel_id)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 66, in get_channel_ref
    text = self.get_uri_data(self.plugin_obj.unc_daddylive_base +
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\plugins\plugin_channels.py", line 105, in get_uri_data
    resp = self.plugin_obj.http_session.get(_uri, headers=header, timeout=8)
AttributeError: 'NoneType' object has no attribute 'get'
2023-12-22 01:35:37,566-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\cabernet\lib\clients\web_tuner.py", line 129, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 291, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\clients\web_tuner.py", line 53, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "C:\Program Files\cabernet\lib\clients\web_tuner.py", line 219, in do_tuning
    self.ffmpeg_proxy.stream(station_data, self.wfile, resp['tuner'])
  File "C:\Program Files\cabernet\lib\streams\ffmpeg_proxy.py", line 73, in stream
    channel_uri = self.get_stream_uri(self.channel_dict)
  File "C:\Program Files\cabernet\lib\streams\stream.py", line 87, in get_stream_uri
    return self.plugins.plugins[_channel_dict['namespace']] \
  File "C:\Program Files\cabernet\lib\plugins\plugin_obj.py", line 106, in get_channel_uri_ext
    return self.instances[_instance].get_channel_uri(_sid)
  File "C:\Program Files\cabernet\lib\plugins\plugin_instance_obj.py", line 85, in get_channel_uri
    return self.channels.get_channel_uri(sid)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 85, in get_channel_uri
    ch_url = self.get_channel_ref(_channel_id)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 66, in get_channel_ref
    text = self.get_uri_data(self.plugin_obj.unc_daddylive_base +
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\plugins\plugin_channels.py", line 105, in get_uri_data
    resp = self.plugin_obj.http_session.get(_uri, headers=header, timeout=8)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 444, in run
    self.stream_uri = self.get_stream_uri()
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 529, in get_stream_uri
    return self.plugins.plugins[self.channel_dict['namespace']] \
  File "C:\Program Files\cabernet\lib\plugins\plugin_obj.py", line 106, in get_channel_uri_ext
    return self.instances[_instance].get_channel_uri(_sid)
  File "C:\Program Files\cabernet\lib\plugins\plugin_instance_obj.py", line 85, in get_channel_uri
    return self.channels.get_channel_uri(sid)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 85, in get_channel_uri
    ch_url = self.get_channel_ref(_channel_id)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 66, in get_channel_ref
    text = self.get_uri_data(self.plugin_obj.unc_daddylive_base +
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\plugins\plugin_channels.py", line 105, in get_uri_data
    resp = self.plugin_obj.http_session.get(_uri, headers=header, timeout=8)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 310, in run
    queue_item = STREAM_QUEUE.get()
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\queues.py", line 97, in get
    res = self._recv_bytes()
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 347, in run
    clear_queues()
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 737, in clear_queues
    clear_q(STREAM_QUEUE)
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 723, in clear_q
    q.get_nowait()
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\queues.py", line 129, in get_nowait
    return self.get(False)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\queues.py", line 109, in get
    elif not self._poll():
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\connection.py", line 257, in poll
    return self._poll(timeout)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\multiprocessing\connection.py", line 328, in _poll
    _winapi.PeekNamedPipe(self._handle)[0] != 0):
BrokenPipeError: [WinError 109] The pipe has been ended
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 444, in run
    self.stream_uri = self.get_stream_uri()
  File "C:\Program Files\cabernet\lib\streams\m3u8_queue.py", line 529, in get_stream_uri
    return self.plugins.plugins[self.channel_dict['namespace']] \
  File "C:\Program Files\cabernet\lib\plugins\plugin_obj.py", line 106, in get_channel_uri_ext
    return self.instances[_instance].get_channel_uri(_sid)
  File "C:\Program Files\cabernet\lib\plugins\plugin_instance_obj.py", line 85, in get_channel_uri
    return self.channels.get_channel_uri(sid)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 85, in get_channel_uri
    ch_url = self.get_channel_ref(_channel_id)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 159, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\plugins_ext\provider_video_daddylive\lib\channels.py", line 66, in get_channel_ref
    text = self.get_uri_data(self.plugin_obj.unc_daddylive_base +
  File "C:\Program Files\cabernet\lib\common\decorators.py", line 63, in wrapper_func
    x = f(self, *args, **kwargs)
  File "C:\Program Files\cabernet\lib\plugins\plugin_channels.py", line 105, in get_uri_data
    resp = self.plugin_obj.http_session.get(_uri, headers=header, timeout=8)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by rocky4546** [comment]
it is related to the updates, hang on and will fix...

**Comment by rocky4546** [comment]
RC12 fixes all channel exceptions from the pickling

**Comment by purplescorpion1** [comment]
> RC12 fixes all channel exceptions from the pickling

confirmed - all working now thanks

**Comment by cookieisland** [comment]
> yea, got the same results. Trying to fix this with covid, so brain is kinda mush.

ouch. Get well soon!
