### ISSUE TITLE
Xumo plugin not working.

### ISSUE THREAD

**Issue by Protektor-Desura** [cabernetwork/cabernet#15]
I am getting this error when I try and use the Xumo plugin to pull in streams from Xumo. I should mention I am running the latest docker version.

image: ghcr.io/cabernetwork/cabernet:latest

Cabernet v0.9.7.5

```Initializing plugin PlutoTV
Initializing plugin M3U
Initializing plugin XUMO
Traceback (most recent call last):
  File "/app/tvh_main.py", line 23, in <module>
    main.main(script_dir)
  File "/app/lib/main.py", line 127, in main
    plugins = init_plugins(config_obj)
  File "/app/lib/main.py", line 181, in init_plugins
    plugins.initialize_plugins()
  File "/app/lib/plugins/plugin_handler.py", line 90, in initialize_plugins
    plugin.plugin_obj = plugin.init_func(plugin)
  File "/app/plugins/provider_video_xumo/__init__.py", line 26, in start
    return XUMO(plugin)
  File "/app/plugins/provider_video_xumo/lib/xumo.py", line 35, in __init__
    self.geo = Geo(_plugin.config_obj, self.namespace.lower())
  File "/app/plugins/provider_video_xumo/lib/geo.py", line 40, in __init__
    self.get_geo()
  File "/app/lib/common/decorators.py", line 104, in wrapper_func
    return f(self, *args, **kwargs)
  File "/app/lib/common/decorators.py", line 49, in wrapper_func
    x = f(self, *args, **kwargs)
  File "/app/plugins/provider_video_xumo/lib/geo.py", line 60, in get_geo
    re.findall(b'__JOBS_REHYDRATE_STATE__=(.+?);</script>', (resp.read()), flags=re.DOTALL)[0])
IndexError: list index out of range


[loggers]
keys = root

[logger_root]
level = DEBUG
handlers = filehandler,loghandler

[handlers]
keys = loghandler, filehandler

[formatters]
keys = extend,simple

[handler_filehandler]
enabled = True
level = DEBUG
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)

[handler_loghandler]
enabled = True
level = DEBUG
class = StreamHandler
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s

[formatter_simple]
format = %(levelname)s:%(module)s %(message)s

[main]
uuid = 013F2F78-0731-11ED-AA9C-0242AC120006
memory_usage = True

[hdhomerun]
hdhr_id = 1058C93A
udp_netmask = 192.168.50.10/24
disable_hdhr = False

[m3u_default]
label = M3U Instance
enabled = True
player-tuner_count = 5

[plutotv_default]
label = PlutoTV Instance
enabled = True
program_thumbnail = poster
player-tuner_count = 5
epg-hours = 12
channel-import_groups = True
player-play_all_segments = True

[ustvgo_default]
label = USTVGO Instance
enabled = True
player-tuner_count = 5
channel-import_groups = True
player-play_all_segments = True

[xumo_default]
label = XUMO Instance
enabled = True
player-tuner_count = 5

[epg]
genre = normal

[ssdp]
udp_netmask = 192.168.50.10/24

[web]
plex_accessible_ip = 192.168.50.10
concurrent_listeners = 10

[m3u]
label = M3U Instance
enabled = True
player-tuner_count = 5

[display]
display_level = 3-Advanced

[channels]
thumbnail_size = Large(180)
```

**Comment by rocky4546** [comment]
I have a fix in the next release (0.9.7.6)
