### ISSUE TITLE
Issue with Tvguide plugin

### ISSUE THREAD

**Issue by poonab** [cabernetwork/cabernet#50]
Not sure if i'm doing something wrong but I've added the tvguide plugin to a docker image built from Dockerfile_tvh_crypt.alpine and get the below error on starting, works fine if plugin isn't present

```
Traceback (most recent call last):
  File "/app/lib/plugins/plugin_handler.py", line 64, in collect_plugins
    importlib.resources.read_text(_plugins_pkg, folder)
  File "/usr/local/lib/python3.8/importlib/resources.py", line 169, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "/usr/local/lib/python3.8/importlib/resources.py", line 125, in open_text
    return TextIOWrapper(reader.open_resource(resource), encoding, errors)
  File "<frozen importlib._bootstrap_external>", line 1048, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/app/plugins_ext/provider_epg_tvguide'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/tvh_main.py", line 23, in <module>
    main.main(script_dir)
  File "/app/lib/main.py", line 135, in main
    plugins = init_plugins(config_obj)
  File "/app/lib/main.py", line 189, in init_plugins
    plugins = plugin_handler.PluginHandler(_config_obj)
  File "/app/lib/plugins/plugin_handler.py", line 44, in __init__
    self.collect_plugins(self.config_obj.data['paths']['external_plugins_pkg'])
  File "/app/lib/plugins/plugin_handler.py", line 67, in collect_plugins
    plugin = Plugin(self.config_obj, self.plugin_defn, '.'.join([_plugins_pkg, folder]))
  File "/app/lib/plugins/plugin.py", line 63, in __init__
    self.load_plugin_manifest(_plugin_defn)
  File "/app/lib/plugins/plugin.py", line 149, in load_plugin_manifest
    self.import_manifest()
  File "/app/lib/plugins/plugin.py", line 159, in import_manifest
    self.namespace = settings['name']
KeyError: 'name'
```

**Comment by rocky4546** [comment]
Confirm you added plugin at the correct folder level.  It should be cabernet/plugins_ext/provider_epg_tvguide/plugin.json
If the file is not found at that level, go back to the release zip and find the correct folder to copy over...

**Comment by poonab** [comment]
Yep that's the location I've got

```
pi@pitv:/tmp/cabernet/plugins_ext/provider_epg_tvguide $ ls -l
total 32
-rw-r--r-- 1 pi pi 1353 Mar 11 15:54  config_defn.json
-rw-r--r-- 1 pi pi  884 Mar 11 15:54  __init__.py
-rw-r--r-- 1 pi pi 1557 Mar 11 15:54  instance_defn.json
drwxr-xr-x 2 pi pi 4096 Mar 11 15:12  lib
-rw-r--r-- 1 pi pi 1214 Mar 11 15:54  LICENSE
-rw-r--r-- 1 pi pi  816 Mar 11 15:54  plugin.json
drwxr-xr-x 2 pi pi 4096 Mar 11 15:12  resources
-rw-r--r-- 1 pi pi  150 Mar 11 15:54 'TOS License.txt'
```

**Comment by rocky4546** [comment]
I may need to put in a fix for this case, but can you please check the config.ini and let me know your daddylive sections and the tvguide sections in the file.

**Comment by poonab** [comment]
[daddylive_default]
label = DaddyLive Instance
enabled = True
channel-import_groups = True

[tvguide_default]
label = TVGuide Instance

[daddylive]
enabled = True
epg-plugin = ALL

**Comment by rocky4546** [comment]
Thanks, your data is all correct.  The issue is caused by the testing I am doing for the plugin manager.  Sorry about that.  Please use version 0.1.5 of the tvguide plugin.

The plugin manager is pulling stuff directly from github, so I needed to make some changes to that plugin.

**Comment by poonab** [comment]
Brilliant, that solved it, thanks
