### ISSUE TITLE
pluto tv plugin error cabernet Version: 0.9.11.00-RC1 ota updated

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#52]
i gte this error when runing pluto tv using streamlink proxy. the pluto tv channels dont play.

C:\cygwin64\home\user\PlutoIPTV>pause
Press any key to continue . . . 2023-03-23 05:10:45,044-WARNING:main #########################################
2023-03-23 05:10:45,045-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546
2023-03-23 05:10:45,046-WARNING:db plugins Add request ignored, retrying 4, no such table: repos
2023-03-23 05:10:45,586-WARNING:db plugins Add request ignored, retrying 3, no such table: repos
2023-03-23 05:10:46,268-WARNING:db plugins Add request ignored, retrying 2, no such table: repos
2023-03-23 05:10:47,028-WARNING:db plugins Add request ignored, retrying 1, no such table: repos
2023-03-23 05:10:47,524-WARNING:db plugins Add request ignored, retrying 0, no such table: repos
2023-03-23 05:10:48,405-WARNING:db plugins GET request ignored retrying 4, no such column: repo
2023-03-23 05:10:48,826-WARNING:db plugins GET request ignored retrying 3, no such column: repo
2023-03-23 05:10:49,337-WARNING:db plugins GET request ignored retrying 2, no such column: repo
2023-03-23 05:10:49,895-WARNING:db plugins GET request ignored retrying 1, no such column: repo
2023-03-23 05:10:50,484-WARNING:db plugins GET request ignored retrying 0, no such column: repo
Traceback (most recent call last):
  File "Z:\cabernet\tvh_main.py", line 41, in <module>
    main.main(script_dir)
  File "Z:\cabernet\lib\main.py", line 136, in main
    plugins = init_plugins(config_obj)
  File "Z:\cabernet\lib\main.py", line 190, in init_plugins
    plugins = plugin_handler.PluginHandler(_config_obj)
  File "Z:\cabernet\lib\plugins\plugin_handler.py", line 45, in __init__
    self.repos.load_cabernet_repo()
  File "Z:\cabernet\lib\plugins\repo_handler.py", line 55, in load_cabernet_repo
    self.update_plugins(repo_settings)
  File "Z:\cabernet\lib\plugins\repo_handler.py", line 88, in update_plugins
    plugin_data = self.plugin_db.get_plugins(_installed=None, _repo=_repo_settings['id'], _plugin_id=plugin['id'])
  File "Z:\cabernet\lib\db\db_plugins.py", line 187, in get_plugins
    for row in rows:
TypeError: 'NoneType' object is not iterable

**Comment by merrychrishna** [comment]
nevermind. cancel this issue. i made a mistake. i didnt realise all my settings had reset, probably a while ago since i last used it or when i replaced the data folder. it was user error, i forgot to set the ffmpeg paths and the streamlink path.

**Comment by rocky4546** [comment]
The error says you did not upgrade correctly and should have nothing to do with the config.ini file.  The new version adds the repo table to the plugins database and it is currently missing causing the errors.  If you continue to get the errors, checkout the release notes which instructs on how to upgrade on this RC.

**Comment by merrychrishna** [comment]
ohhh ok sweet that did it. thanks
