### ISSUE TITLE
Backups fails on Windows with Daddylive plugin

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#84]
2023-04-19 19:14:10,694-ERROR:scheduler UNEXPECTED EXCEPTION on GET='charmap' codec can't encode characters in position 74-77: character maps to <undefined>
Traceback (most recent call last):
  File "Z:\cabernet\lib\schedule\scheduler.py", line 141, in call_trigger
    results = call_f(self.plugins)
  File "Z:\cabernet\lib\db\datamgmt\backups.py", line 62, in backup_data
    b.backup_data()
  File "Z:\cabernet\lib\db\datamgmt\backups.py", line 92, in backup_data
    Backup.call_backup(key, self.config, backup_folder=new_backup_path)
  File "Z:\cabernet\lib\common\decorators.py", line 232, in call_backup
    inst_fn(**kwargs)
  File "Z:\cabernet\lib\db\db_channels.py", line 411, in backup
    self.export_sql(backup_folder)
  File "Z:\cabernet\lib\db\db.py", line 313, in export_sql
    export_f.write('%s\n' % line)
  File "C:\Users\User0\AppData\Local\Programs\Python\Python395\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 74-77: character maps to <undefined>

**Comment by rocky4546** [comment]
Fixed in 0.9.12.15
