### ISSUE TITLE
Cabernet 0.9.13.00-RC1  - Unable to start stream

### ISSUE THREAD

**Issue by itprotj** [cabernetwork/cabernet#89]
Appears the new version has a bug when attempting to start a stream

`2023-04-30 21:29:50,140-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 5331d5fb753499095a00045a
2023-04-30 21:29:50,140-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:29:50,982-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 545943f1c9f133a519bbac92
2023-04-30 21:29:50,983-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:29:51,017-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 545943f1c9f133a519bbac92
2023-04-30 21:29:51,018-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:30:01,400-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 569546031a619b8f07ce6e25
2023-04-30 21:30:01,401-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:30:02,571-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 569546031a619b8f07ce6e25
2023-04-30 21:30:02,572-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:30:07,677-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 569546031a619b8f07ce6e25
2023-04-30 21:30:07,677-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:30:37,793-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 569546031a619b8f07ce6e25
2023-04-30 21:30:37,794-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:31:46,402-DEBUG:web_handler [192.168.80.7] "GET /M3U/othertv/channels.m3u HTTP/1.1" 200 -
2023-04-30 21:31:46,559-DEBUG:web_handler [192.168.80.7] "GET /M3U/PlutoTVCustom/channels.m3u HTTP/1.1" 200 -
2023-04-30 21:31:46,603-DEBUG:web_handler [192.168.80.7] "GET /M3U/SamsungTVPlus/channels.m3u HTTP/1.1" 200 -
2023-04-30 21:32:13,156-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 569546031a619b8f07ce6e25
2023-04-30 21:32:13,156-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'
2023-04-30 21:32:15,288-NOTICE:web_tuner M3U:plutotvcustom Tuning to channel 569546031a619b8f07ce6e25
2023-04-30 21:32:15,289-ERROR:web_tuner UNEXPECTED EXCEPTION on GET='VOD'
Traceback (most recent call last):
  File "/opt/cabernet/lib/clients/web_tuner.py", line 128, in do_GET
    if gettunerrequest.call_url(self, self.content_path):
  File "/opt/cabernet/lib/common/decorators.py", line 315, in call_url
    self.url2func[uri](_webserver, *args, **kwargs)
  File "/opt/cabernet/lib/clients/web_tuner.py", line 52, in watch
    _webserver.do_tuning(sid, _webserver.query_data['name'], _webserver.query_data['instance'])
  File "/opt/cabernet/lib/clients/web_tuner.py", line 204, in do_tuning
    station_data['display_number'], station_data['json']['VOD'])
KeyError: 'VOD'`

**Comment by rocky4546** [comment]
This occurs with M3U plugin only.  I like simple fixes.  Patched Cabernet and also updated the M3U Plugin (but not needed for fix) so it will have the VOD status in the long run.

Checkout 0.9.13.00-RC2

**Comment by itprotj** [comment]
Thankyou good sir!
